<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your password is invalid</name>
   <tag></tag>
   <elementGuidId>55112bf9-4a66-4549-a124-67743d3b3e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flash']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fa9042e3-61e4-4dac-9b4e-835d316979a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash</value>
      <webElementGuid>d6f3416b-3073-4b5d-ae53-73c1aa379a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flash error</value>
      <webElementGuid>ce815287-1f7d-4757-962e-2bfe7d1bcee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Your password is invalid!
            ×
          </value>
      <webElementGuid>0d9ca893-9934-49a8-a0cf-3bea36039479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash&quot;)</value>
      <webElementGuid>7b062153-414b-4285-b3fa-d9867e1f72bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flash']</value>
      <webElementGuid>f84fcf1c-4e35-4f96-b638-d1c3fefceb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash-messages']/div</value>
      <webElementGuid>35324409-81e2-4682-a197-ed9080df4cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Page'])[1]/preceding::div[1]</value>
      <webElementGuid>9fcbf4f8-5fb3-445d-919e-43feea85dee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tomsmith'])[1]/preceding::div[1]</value>
      <webElementGuid>7b2dc4da-c067-49c6-a3d1-fb402a3c0aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your password is invalid!']/parent::*</value>
      <webElementGuid>b2f10782-f0dd-4ef5-ac3b-a27d0e0ffc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>726f532a-397d-48a4-9799-92099c4c2d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flash' and (text() = '
            Your password is invalid!
            ×
          ' or . = '
            Your password is invalid!
            ×
          ')]</value>
      <webElementGuid>818c8b7f-5450-4e5d-b1d9-5b7b878c9bf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
